# Generated by Django 4.1.5 on 2023-03-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Donator',
        ),
        migrations.RenameField(
            model_name='donator',
            old_name='description',
            new_name='amount',
        ),
    ]
